# Create deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demo-app
  template:
    metadata:
      labels:
        app: python-demo-app
    spec:
      containers:
      - name: python-demo-app
        image: mohitsharma11/test:python-test-app 
        ports:
        - containerPort: 5000

# Create service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-demo-app-service
spec:
  selector:
    app: python-demo-app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
